import React from 'react';

// Dictionnaire des modèles par marque (extrait, à compléter si besoin)
const carModelsByBrand = {
  'Acura':
    [
      'CL',
      'CSX',
      'EL',
      'ILX',
      'Integra',
      'Legend',
      'MDX',
      'NSX',
      'RDX',
      'RL',
      'RLX',
      'RSX',
      'SLX',
      'TL',
      'TLX',
      'TSX',
      'Vigor',
      'ZDX', 
    ],
  'Alfa Romeo': 
    [
      '155 (1992-1998)',
      '145/146 (1994-2001)',
      'GTV et Spider (1995-2006)',
      '156 (1997-2006)',
      'Scighera (1997)',
      '166 (1998-2007)',
      '147 (2000-2010)',
      'GT (2004-2010)',
      'MiTo (2008-2018)',
      'TZ3 Zagato (2010)',
      'Brera (2005-2010)',
      'Spider (2006-2010)',
      '8C Competizione (2008-2010)',
      '8C Spider (2008-2010)',
      '159 (2005-2011)',
      'Giulietta (2010-2020)',
      'Giulia',
      'Junior',
      'Tonale',
      'Stelvio',
    ],
  'Audi': 
    [
      '50',
      '60',
    '80',
    '80 I',
    '80 II',
    '80 III',
    '80 IV',
    '90',
    '90 quattro IMSA GTO',
    '100',
    '100 I',
    '100 II',
    '100 III',
    '100 Coupé S',
    '200',
    '200 I',
    '200 II',
    '200 quattro Trans-Am',
    '225',
    '920',
    'A1',
    'A1 I',
    'A1 II',
    'A2',
    'A3',
    'A3 I',
    'A3 II',
    'A3 III',
    'A3 IV',
    'A4',
    'A4 I',
    'A4 II',
    'A4 III',
    'A4 IV',
    'A4 allroad quattro',
    'A4 V',
    'A4 DTM',
    'A4 Cabriolet',
    'A5',
    'A5 I',
    'A5 II',
    'A5 DTM',
    'A5 III',
    'A6',
    'A6 I',
    'A6 II',
    'A6 III',
    'A6 IV',
    'A6 V',
    'A6 e-tron',
    'A7',
    'A7 I',
    'A7 II',
    'A8',
    'A8 I',
    'A8 II',
    'A8 III',
    'A8 IV',
    'Allroad Quattro',
    'e-tron',
    'Front 225',
    'R8',
    'R8R',
    'Cabriolet',
    'Coupé',
    'Coupé GT',
    'DKW F1',
    'e-tron GT',
    'Q8 e-tron',
    'Q8 e-tron Sportback',
    'Front',
    'Italdesign DaVinci',
    'NSU Ro 80',
    'NSU Spider',
    'Nuvolari Quattro',
    'Pikes Peak Quattro',
    'Q2',
    'Q3',
    'Q3 I',
    'Q3 II',
    'Q3 Sportback',
    'Q4 e-tron',
    'Q5',
    'Q5 I 8R',
    'Q5 II',
    'Q5 III',
    'Q5 Sportback',
    'Q6 e-tron',
    'Q6 e-tron Sportback',
    'Q7',
    'Q7 4L',
    'Q7 4M',
    'Q8',
    'Quattro',
    'Quattro (compétition)',
    'R8 (routière)',
    'R8 (Type 42)',
    'R8 (voiture de course)',
    'R8 (Type 4S)',
    'R8 LMS',
    'R8 LMS GT3',
    'R8 LMS GT4',
    'R8C',
    'R10 TDI',
    'R18 e-tron quattro',
    'R18 TDI',
    'R18 Ultra',
    'R18 e-tron quattro (2014-2015)',
    'R18 (2016)',
    'RS 3 LMS',
    'RS Q3',
    'RS2',
    'RS4',
    'RS5',
    'RS6',
    'RS7',
    'RS8',
    'S1',
    'S2',
    'S4',
    'S4 C4',
    'S5',
    'S6',
    'S6 Plus',
    'S8',
    'TT',
    'TT 8J',
    'TT 8N',
    'TT FV',
    'TT-R',
    'Type C Alpensieger',
    'Type A',
    'Type B',
    'Type D',
    'Type E',
    'Type G',
    'Type K',
    'Type M',
    'Type P',
    'Type R Imperator',
    'Type T',
    'UW',
    'V8',
    'V8 quattro DTM',
    'Zwickau',
    ],
  'BMW': ['1 Series', '3 Series', '5 Series', 'X1', 'X3'],
  'BYD': [],
  'Chery': [],
  'Chevrolet': ['Spark', 'Malibu', 'Camaro', 'Equinox', 'Tahoe'],
  'Citroën': [],
  'Dacia': [],
  'Dongfeng': [],
  'Infiniti': [],
  'Isuzu': [],
  'Fiat': [],
  'Ford': ['Fiesta', 'Focus', 'Mustang', 'Puma', 'Kuga'],
  'Geely': [],
  'Genesis': [],
  'Great Wall': [],
  'Honda': ['Civic', 'Accord', 'CR-V', 'Jazz', 'HR-V'],
  'Hyundai': ['i10', 'i20', 'i30', 'Tucson', 'Kona'],
  'Jaguar': [],
  'Jeep': [],
  'Kia': ['Picanto', 'Rio', 'Ceed', 'Sportage', 'Sorento'],
  'Land Rover': [],
  'Lexus': [],
  'Lincoln': [],
  'Mahindra': [],
  'Mazda': [],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'GLA', 'GLC'],
  'Mini': [],
  'Mitsubishi': [],
  'Nissan': ['Micra', 'Juke', 'Qashqai', 'Leaf', 'X-Trail'],
  'Opel': [],
  'Perodua': [],
  'Peugeot': [],
  'Porsche': [],
  'Proton': [],
  'Ram': [],
  'Renault': [],
  'Saab': [],
  'Seat': [],
  'Skoda': [],
  'Smart': [],
  'SsangYong': [],
  'Subaru': [],
  'Suzuki': [],
  'Tata': [],
  'Tesla': [],
  'Toyota':
    [
      'Aygo',
      'Aygo X',
      'Auris',
      'Avensis',
      'bZ4X',
      'C-HR',
      'C-HR II',
      'Corolla',
      'GR86',
      'Highlander',
      'Hilux',
      'Land Cruiser',
      'Mirai',
      'Prius',
      'ProAce',
      'ProAce City',
      'ProAce City Verso',
      'ProAce Verso',
      'Rav4',
      'Supra',
      'Yaris',
      'Yaris Cross'
    ],
  'Volkswagen': 
  [
    'Golf',
    'Polo',
    'Passat',
    'Tiguan',
    'T-Roc',
  ],
  'Volvo': [],
  // ... ajoutez d'autres marques et modèles si besoin
};

export default function CarModelSelect({ brand, value, onChange }) {
  const models = carModelsByBrand[brand] || [];
  return (
    <div>
      <label htmlFor="car-model-select">Modèle : </label>
      <select id="car-model-select" value={value} onChange={onChange} required disabled={!brand}>
        <option value="">-- Sélectionnez un modèle --</option>
        {models.map((model) => (
          <option key={model} value={model}>{model}</option>
        ))}
      </select>
    </div>
  );
}
